version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  ignore:
  - dependency-name: webpacker
    versions:
    - 5.2.2
  - dependency-name: rails-i18n
    versions:
    - 6.0.0
    - 6.0.0
    - 6.0.0
    - 6.0.0
    - 6.0.0
    - 6.0.0
    - 6.0.0
  - dependency-name: rails
    versions:
    - 6.1.2.1
    - 6.1.2.1
    - 6.1.3
    - 6.1.3
    - 6.1.3
    - 6.1.3.1
    - 6.1.3.1
  - dependency-name: web-console
    versions:
    - 4.1.0
    - 4.1.0
    - 4.1.0
    - 4.1.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
    - 5.0.0
  - dependency-name: aws-sdk-s3
    versions:
    - 1.88.2
    - 1.90.0
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.9.0
    - 1.9.1
  - dependency-name: capybara
    versions:
    - 3.35.2
  - dependency-name: bootsnap
    versions:
    - 1.6.0
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - danirod
  assignees:
  - danirod
  labels:
  - dependencies
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
  commit-message:
    prefix: chore
    include: scope
