require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'node_modules/**/*'
    - 'db/schema.rb'

# Allow scenario to describe Capybara E2E tests.
Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*.rb'

# I see nothing wrong with this.
RSpec/ExampleLength:
  Enabled: false

# Documentation in a Rails app? No thanks.
Style/Documentation:
  Enabled: false

# Rails actually suggests using this approach when setting redirect rules.
# https://guides.rubyonrails.org/routing.html#redirection. Therefore, I'll
# be ignoring config/routes.rb.
Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - namespace
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - config/routes.rb

# There are some boilerplate secret keys in the devise.rb file that I'd rather not touch.
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
