require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'
    - 'tmp/**/*'

inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

# Rails actually suggests using this approach when setting redirect rules.
# https://guides.rubyonrails.org/routing.html#redirection. Therefore, I'll
# be ignoring config/routes.rb.
Style/FormatStringToken:
  Exclude:
    - config/routes.rb
