language: ruby
branches:
  only:
    - master
rvm: 2.4.1
services:
  - postgresql
env:
  - DB_USERNAME=postgres
before_install:
  - nvm install 6
  - nvm use 6
  - node -v
  - npm install -g yarn
before_script:
- bundle exec rake db:create yarn:install
- RAILS_ENV=test bundle exec rails webpacker:compile
script: bundle exec rspec spec
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
