language: ruby
branches:
  only:
    - master
rvm:
  - 2.3.3
  - 2.3.4
  - 2.4.1
services:
  - postgresql
env:
  - DB_USERNAME=postgres
before_install:
  - nvm install --lts
  - nvm use --lts
  - node -v
  - npm install -g yarn
before_script: bundle exec rake db:create yarn:install
script: bundle exec rspec spec
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
