version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - danirod
    default_assignees:
    - danirod
    default_labels:
    - dependencies
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
    - danirod
    default_assignees:
    - danirod
    default_labels:
    - dependencies
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: docker
    directory: /
    update_schedule: weekly
    default_reviewers:
    - danirod
    default_assignees:
    - danirod
    default_labels:
    - dependencies
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: docker
    directory: /spec
    update_schedule: weekly
    default_reviewers:
    - danirod
    default_assignees:
    - danirod
    default_labels:
    - dependencies
    commit_message:
      prefix: "chore"
      include_scope: true
