name: Build Docker image

on: [push]

jobs:
  docker_registry:
    name: Compile Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Dockerfile
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/makigas:latest .
